### ISSUE TITLE
Getting Error: Cannot find module 'coffee-script'

### ISSUE THREAD

**Issue by pisaacs** [tyronewilson/protractor-rails#1]
I really appreciate you kicking the tires on this gem that will help to further the rails-angularjs ecosystem. I went through the setup and got the point where I ran `rake protractor:spec` ; however, I got the below error message. Any thoughts? I also tried removing `'protractor_specs/**/*.coffee'` from the protractor.conf.js file but that didn't help. 

```
[2014-04-06 23:14:46] INFO  WEBrick 1.3.1
[2014-04-06 23:14:46] INFO  ruby 2.0.0 (2013-05-14) [x86_64-darwin12.4.0]
[2014-04-06 23:14:46] INFO  WEBrick::HTTPServer#start: pid=21652 port=4000

module.js:340
    throw err;
          ^
Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by marioidival** [comment]
this fixes don't work
error:
``` vlog(2, () => this + ' scheduling notifications', this);```
