### ISSUE TITLE
Running rake protractor:init fails after 

### ISSUE THREAD

**Issue by itsryandrake** [tyronewilson/protractor-rails#39]
$ rake protractor:install
$ rake protractor:init   

Console error:

```rake aborted!
undefined method `configuration' for Protractor:Module
lib/tasks/install.rake:42:in `block (2 levels) in <top (required)>'
/Users/ryandrake/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/ryandrake/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => protractor:init
(See full trace by running task with --trace)
```

**Comment by itsryandrake** [comment]
$ rake protractor:example

```
rake aborted!
undefined method `present?' for nil:NilClass
lib/tasks/protractor.rake:21:in `write_log': undefined method `present?' for nil:NilClass (NoMethodError)
	from lib/tasks/protractor.rake:105:in `block (2 levels) in <top (required)>'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/task.rb:236:in `call'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/task.rb:236:in `block in execute'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/task.rb:231:in `each'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/task.rb:231:in `execute'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
	from /Users/ryandrake/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/task.rb:161:in `invoke'
	from lib/tasks/protractor.rake:8:in `block (3 levels) in <top (required)>'
	from lib/tasks/protractor.rake:7:in `fork'
	from lib/tasks/protractor.rake:7:in `block (2 levels) in <top (required)>'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/task.rb:236:in `call'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/task.rb:236:in `block in execute'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/task.rb:231:in `each'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/task.rb:231:in `execute'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
	from /Users/ryandrake/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/task.rb:161:in `invoke'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/application.rb:149:in `invoke_task'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/application.rb:106:in `each'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/application.rb:106:in `block in top_level'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/application.rb:115:in `run_with_threads'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/application.rb:100:in `top_level'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/application.rb:78:in `block in run'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/bin/rake:23:in `load'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/bin/rake:23:in `<main>'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ryandrake/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
lib/tasks/protractor.rake:21:in `write_log'
lib/tasks/protractor.rake:85:in `block (2 levels) in <top (required)>'
lib/tasks/protractor.rake:15:in `ensure in block (2 levels) in <top (required)>'
lib/tasks/protractor.rake:16:in `block (2 levels) in <top (required)>'
```

**Comment by ProGM** [comment]
Are you running protractor in a rails project?
